# Generated by Django 3.2.10 on 2022-06-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Картинка поста'),
        ),
    ]
