# Generated by Django 3.2.10 on 2021-12-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.CharField(default='htfrfghjydhrtsrtshrsht', max_length=400, verbose_name='Описание блога'),
            preserve_default=False,
        ),
    ]
