# Generated by Django 3.2.10 on 2021-12-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postitem',
            name='comments_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество комментариев'),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='quizzes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество опросников'),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
