# Generated by Django 3.2.10 on 2021-12-24 07:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0004_blog_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blog',
            unique_together={('title', 'owner')},
        ),
    ]
