# Generated by Django 3.2.10 on 2021-12-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blog_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='slug',
            field=models.SlugField(default='qweqweeqw', verbose_name='Путь поста'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='postitem',
            unique_together={('title', 'blog')},
        ),
    ]
