# Generated by Django 3.2.10 on 2022-04-30 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_subscription_subscribe_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscribe_status',
            new_name='subscription_status',
        ),
    ]
