# Generated by Django 3.2.10 on 2022-06-02 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0010_auto_20220505_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passedquestion',
            name='question',
        ),
        migrations.AddField(
            model_name='passedquestion',
            name='answer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='passed_questions', to='blogs.answer', verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='passedquestion',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='passed_question', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь который дал ответ'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(default='', verbose_name='Путь опроса'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='', max_length=70, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(default='', max_length=70, verbose_name='Ответ на вопрос'),
        ),
    ]
