# Generated by Django 3.2.10 on 2022-06-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_alter_passedquestion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Путь опроса'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='', max_length=70, unique=True, verbose_name='Вопрос'),
        ),
    ]
